# Generated by Django 2.0.6 on 2019-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
